dist: trusty
os: linux
language: php
php:
- '7.1.14'
services:
- mysql
install:
- mysql -e 'CREATE DATABASE aurora;'
- composer install
- composer run pre-config
script:
- php ./travis.php
- chmod +x ./travis.sh
- ./travis.sh -t npm
- ./travis.sh -t build
- ./travis.sh -t pack
- chmod +x ./travis-plesk-builder.sh
- ./travis-plesk-builder.sh -t build
- ./travis-plesk-builder.sh -t log
- ./travis-plesk-builder.sh -t zip
after_success: 
- ./travis.sh -t upload
- ./travis-plesk-builder.sh -t upload
env:
  global:
  - PRODUCT_NAME=webmail-lite
  - PLESK_PRODUCT_TITLE="WebMail Lite"
  - PLESK_PRODUCT_FULLTITLE="Afterlogic WebMail Lite"
  - PLESK_PRODUCT_WEBSITE=https://www.afterlogic.com/webmail-lite
  - PLESK_PRODUCT_DOWNLOAD=https://www.afterlogic.com/download/webmail-lite
